{{- if not (hasKey .Values "secretsName") }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "ps-database.fullname" . }}-secrets
  labels:
{{ include "ps-database.labels" . | indent 4 }}
type: Opaque
stringData:
{{ .Values.secrets.passwords | toYaml | indent 2 }}
{{- end -}}
